#!/usr/bin/env bash
LD_LIBRARY_PATH=/home/cpi/apps/nwjs-sdk-v0.27.6-linux-arm/lib /home/cpi/apps/nwjs-sdk-v0.27.6-linux-arm/nw /home/cpi/games/NWJS/$1 --use-gl=egl --ignore-gpu-blacklist --disable-accelerated-2d-canvas --num-raster-threads=2 --remote-debugging-port=9222

